repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=4096']
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
      - id: requirements-txt-fixer
#  - repo: https://github.com/prettier/prettier
#    rev: 1.17.0
#    hooks:
#      - id: prettier
#        files: www/.*\.(js|vue|css)
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.9.0
    hooks:
      -  id: reorder-python-imports
         language_version: python3
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.2
    hooks:
      - id: flake8
